
import 'package:json_annotation/json_annotation.dart';
enum CategoryEnum {
@JsonValue("NONE")
none,
@JsonValue("LAPTOP")
laptop,
@JsonValue("DESKTOP")
desktop,
@JsonValue("CAMERA")
camera,
@JsonValue("MOUSE")
mouse,
@JsonValue("MONITOR")
monitor,
@JsonValue("KEYBOARD")
keyboard,
@JsonValue("TABLET")
tablet,
@JsonValue("SMARTPHONE")
smartphone,
@JsonValue("PRINTER")
printer,
@JsonValue("SCANNER")
scanner,
@JsonValue("SPEAKER")
speaker,
@JsonValue("HEADPHONES")
headphones,
@JsonValue("MICROPHONE")
microphone,
@JsonValue("SMARTWATCH")
smartwatch,
@JsonValue("ROUTER")
router,
@JsonValue("MODEM")
modem,
@JsonValue("HARD_DRIVE")
hardDrive,
@JsonValue("SOLID_STATE_DRIVE")
solidStateDrive,
@JsonValue("USB_DRIVE")
usbDrive,
@JsonValue("MEMORY_CARD")
memoryCard,
@JsonValue("PROJECTOR")
projector,
@JsonValue("GRAPHICS_CARD")
graphicsCard,
@JsonValue("MOTHERBOARD")
motherboard,
@JsonValue("CPU")
cpu,
@JsonValue("RAM")
ram,
@JsonValue("POWER_SUPPLY")
powerSupply,
@JsonValue("CASE_PC")
casePc,
@JsonValue("COOLING_FAN")
coolingFan,
@JsonValue("WEBCAM")
webcam,
@JsonValue("DRONE")
drone,
@JsonValue("VR_HEADSET")
vrHeadset,
@JsonValue("GAME_CONSOLE")
gameConsole,
}

